version: "3.7"

services:
  mysql:
    image: mysql:8
    #platform: linux/x86_64
    container_name: mysql-testcode-real
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: real
      MYSQL_ROOT_PASSWORD: abcd1234
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
