spring:
  datasource:
    url: jdbc:mysql://localhost:13306/real
    username: root
    password: abcd1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    #org.springframework.transaction.interceptor: trace
    handson.testcodejpa: debug
    org.hibernate:
      type:
        descriptor:
          sql: trace
